### ISSUE TITLE
Thread Error with Experienced Worlds and C2ME installed

### ISSUE THREAD

**Issue by lesxmore** [Drathonix/experiencedworlds2#1]
**Mod Version**
experiencedworlds-2.0.2+1.21.3+fabric

**Describe the bug**
Thread Error

**To Reproduce**
1. Install both C2ME and Experienced Worlds Fabric mod.
2. Run the server.

`[01:44:34] [pool-21-thread-1/ERROR]: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: pool-21-thread-1)
This is usually NOT a bug in C2ME, but a bug in another mod or in vanilla code. 
Possible solutions: 
  - Find possible causes in the stack trace below and 
    - if caused by another mod, report this to the corresponding mod authors 
    - if no other mods are involved, report this to C2ME 
java.util.ConcurrentModificationException: ThreadLocalRandom accessed from a different thread (owner: Server thread, current: pool-21-thread-1)
        at knot/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.handleNotOwner(CheckedThreadLocalRandom.java:55) ~[c2me-fixes-worldgen-threading-is.330+1.21.2-2c8c40973d4ab3a7.jar:?]
        at knot/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.isSafe(CheckedThreadLocalRandom.java:38) ~[c2me-fixes-worldgen-threading-is.330+1.21.2-2c8c40973d4ab3a7.jar:?]
        at knot/com.ishland.c2me.fixes.worldgen.threading_issues.common.CheckedThreadLocalRandom.method_43156(CheckedThreadLocalRandom.java:86) ~[c2me-fixes-worldgen-threading-is.330+1.21.2-2c8c40973d4ab3a7.jar:?]
        at knot/net.minecraft.class_6566.method_43048(class_6566.java:33) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_5819.method_39332(class_5819.java:52) ~[server-intermediary.jar:?]
        at knot/com.drathonix.experiencedworlds.common.FairnessFixer.getFairPos(FairnessFixer.java:86) ~[experiencedworlds-2.0.2+1.21.3+fabric.jar:?]
        at knot/com.drathonix.experiencedworlds.common.data.ExperiencedBorderManager.lambda$fixBorder$2(ExperiencedBorderManager.java:95) ~[experiencedworlds-2.0.2+1.21.3+fabric.jar:?]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by Drathonix** [comment]
Classic. I will put out an update soon making world interactions thread-safe. C2ME defeats me once again!

**Comment by lesxmore** [comment]
I would also like to point out that damaging mobs doesn't work while using both mods.

**Comment by Drathonix** [comment]
> I would also like to point out that damaging mobs doesn't work while using both mods.

I don't know why this would be happening. If you could send me your logs the next time this happens that'd be great.

**Comment by Drathonix** [comment]
The thread error has been fixed in 2.0.3. Let me know if the second thing you mention occurs again (with a log)
